### ISSUE TITLE
Python/Django?

### ISSUE THREAD

**Issue by nipython** [merrychap/shellen#1]
Здравствуйте, Михаил!
Сразу хочу извиниться, что пишу вам в гитхаб в issue.
Я ищу разработчика с опытом в Python от 2-х лет до 100 лет (а опыт с Python-ом у вас есть, судя по репозиторию :), пониманием веба, опытом в Django, возможностью разговаривать хотя бы на ломаном английском :)
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (это именно скайп), если это про вас И вам было бы интересно переехать в Минск работать в штате компании на лучших условиях (удаленно мы не можем, увы).
Спасибо

**Comment by merrychap** [comment]
Hello. It's an interesting offer, but I can't right now move to another city (i'm still a student). But anyway, thanks
And about writing job offers in issues. I have the Telegram account, written in the description :D if you have any more questions, then contact me in Telegram, please.
