### ISSUE TITLE
Use prompt_toolkit instead of readline

### ISSUE THREAD

**Issue by fabiocerqueira** [merrychap/shellen#6]
https://github.com/jonathanslenders/python-prompt-toolkit

**Comment by merrychap** [comment]
Thank you very much for this link! Really, I've been searching for this for so long :D

**Comment by merrychap** [comment]
Everything goes wrong after ```clear``` command. I will use colors for prompt from prompt_toolkit itself instead

**Comment by merrychap** [comment]
Now everything works fine
